[features]
seeds = false
[programs.localnet]
root = "HxNNbTXJg3doQmi6c23RDvnbeyiakAAp7NtP5YRCgA3P"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/maxefi/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
