[features]
seeds = false
[programs.localnet]
root = "CKnCEbbP4HH4bTNPQX43wgQToGAiEqZDTGWePWk7ixmC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/maxefi/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
